### ISSUE TITLE
CSS Animation Related Events Aren't Fired

### ISSUE THREAD

**Issue by Rybadour** [karma-runner/karma-chrome-launcher#210]
"animationstart" and "animationend" aren't fired when I run my Javascript with karma-chrome-launcher so I am unable to test my code.

These events are fired when CSS animations are run: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationstart_event

I am triggering these animations with CSS like:
```CSS
@keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
}  
@keyframes fadeOut {
    from { opacity: 1; }
    to { opacity: 0; }
}

.popover:not([visible]) .content.did-fade-in {
    display: inline-block;
    animation: fadeOut 200ms;
}

.popover[visible] .content {
    display: inline-block;
    animation: fadeIn 200ms;
}
```
