### ISSUE TITLE
Chrome 80.0.3987 Disconnectedreconnect failed before timeout of 2000ms (transport close)

### ISSUE THREAD

**Issue by MrNocTV** [karma-runner/karma-chrome-launcher#220]
I've been using the same configuration like this for both local test and pipeline test on Bitbucket. However today I've experienced a weird behavior. The tests run perfectly fine on my local machine with Chrome 80.0.3987 but cannot run on Bitbucket pipeline.

Here's the configuration:
```module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, './coverage/sbs-app'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true,
    failOnEmptyTestSuite: false
  });
};
```

Here's the log on Bitbucket:

```+ npm test
> sbs-app@0.13.0-SNAPSHOT test /opt/atlassian/pipelines/agent/build
> ng test --codeCoverage=true --watch=false
20 03 2020 05:04:29.573:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
20 03 2020 05:04:29.578:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
20 03 2020 05:04:29.709:INFO [launcher]: Starting browser Chrome
20 03 2020 05:05:29.710:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
20 03 2020 05:05:29.733:INFO [launcher]: Trying to start Chrome again (1/2).
20 03 2020 05:05:30.476:INFO [Chrome 80.0.3987 (Linux 0.0.0)]: Connected on socket om5pSm18PZVX8es9AAAA with id 98462470
20 03 2020 05:05:32.942:WARN [Chrome 80.0.3987 (Linux 0.0.0)]: Disconnected (0 times)reconnect failed before timeout of 2000ms (transport close)
Chrome 80.0.3987 (Linux 0.0.0) ERROR
  Disconnectedreconnect failed before timeout of 2000ms (transport close)
Chrome 80.0.3987 (Linux 0.0.0) ERROR
  Disconnectedreconnect failed before timeout of 2000ms (transport close)
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

How I run the test:
```
ng test --codeCoverage=true --watch=false
```

and the dependencies version:
```
"dependencies": {
		"@angular/animations": "^8.2.14",
		"@angular/common": "^8.2.14",
		"@angular/compiler": "^8.2.14",
		"@angular/core": "^8.2.14",
		"@angular/forms": "^8.2.14",
		"@angular/platform-browser": "^8.2.14",
		"@angular/platform-browser-dynamic": "^8.2.14",
		"@angular/router": "^8.2.14",
		"@ngrx/effects": "^8.3.0",
		"@ngrx/store": "^8.3.0",
		"@ngx-translate/core": "^11.0.1",
		"@ngx-translate/http-loader": "^4.0.0",
		"@types/file-saver": "^2.0.1",
		"angular-font-awesome": "^3.1.2",
		"bootstrap": "^3.4.1",
		"classlist.js": "^1.1.20150312",
		"element-remove": "^1.0.4",
		"file-saver": "^2.0.2",
		"font-awesome": "^4.7.0",
		"jquery": "^3.4.1",
		"json2typescript": "^1.2.3",
		"mdn-polyfills": "^5.18.0",
		"ng2-completer": "^3.0.3",
		"ngx-currency": "^2.0.0",
		"rxjs": "~6.4.0",
		"tslib": "^1.10.0",
		"zone.js": "~0.9.1"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "^0.803.24",
		"@angular/cli": "^8.3.19",
		"@angular/compiler-cli": "^8.2.14",
		"@angular/language-service": "^8.2.14",
		"@types/jasmine": "~3.5.0",
		"@types/jasminewd2": "~2.0.8",
		"@types/node": "~8.9.4",
		"codelyzer": "^5.0.0",
		"jasmine-core": "~3.5.0",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "~4.4.1",
		"karma-chrome-launcher": "^3.1.0",
		"karma-coverage-istanbul-reporter": "~2.1.1",
		"karma-jasmine": "~2.0.1",
		"karma-jasmine-html-reporter": "^1.4.2",
		"ngx-spec": "^2.1.4",
		"protractor": "~5.4.2",
		"puppeteer": "^2.1.1",
		"ts-node": "~7.0.0",
		"tslint": "~5.15.0",
		"typescript": "~3.5.3"
	}
```

I've tried numerous ways to resolve this issue, 

Try 1:
```
ng test --code-coverage --no-watch --source-map=false
```

Try 2:
```
    browserDisconnectTimeout: 200000,
    browserDisconnectTolerance: 3,
    browserNoActivityTimeout: 200000,
```

At first glance, I see the previous passed tests on Bitbucket are run with Chrome 76.0.3809, only failed when it's changed to 80.0.3987 but local tests are also run with 80.0.3987 so I'm not sure if Chrome version is the issue.

I've excluded all the tests and rerun again on Bitbucket but got the same issue.

I have no choice but switch to ChromeHeadless and .... it works :| 

```
const process = require('process');
process.env.CHROME_BIN = require('puppeteer').executablePath()

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, './coverage/sbs-app'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadlessNoSandbox'],
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    },
    singleRun: false,
    restartOnFileChange: true,
    failOnEmptyTestSuite: false
  });
};
```

Can someone explain that why changing to ChromeHeadless in this case can resolve the issue?
I cant tell why with the same Chrome version 80.0.3987, it only works on my local machine and doesn't work on Bitbucket so if you can please tell.

**Comment by johnjbarton** [comment]
Please look at your log to verify that the version number of chrome for the failing and passing runs are the same.

Make sure you can run chrome on the remote machine, just execute the process that the launcher would run and verify that it does not crash or fail to find the binary.

**Comment by MrNocTV** [comment]
Hi @johnjbarton I've checked the Chrome's version on the Bitbucket side and on my side multiple times, they are the same. 

However, I don't quite understand this: 

> Make sure you can run chrome on the remote machine, just execute the process that the launcher would run and verify that it does not crash or fail to find the binary.

It's a Bitbucket pipeline that get to run the tests after every commit. We use this config file for the pipeline:

```
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Test
        image: atlassianlabs/docker-node-jdk-chrome-firefox
        caches:
          - node
        script:
          - npm install
          - npm test
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - echo "$(ls -la)"
            - npm install
            - npm install -g @angular/cli
            - npm run-script production
            - echo "$(ls -la dist/)"
          artifacts:
            - dist/**
      - step:
          name: Deploy
          deployment: staging
          trigger: manual
          script:
            - scp -oStrictHostKeyChecking=no -oProxyJump=ops@xxx.io -r dist/ ops@xxx.local:/x/xx/dev
```

The docker image `docker-node-jdk-chrome-firefox` always get the latest version of Chrome. What bothering me is why it works when I change it to `ChromeHeadless`.
